using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Liaison.Biz.Tests.Strings
{
    public static class HHQBnString
    {
        public static string headquartersAndHqBn_38id = @"<CurrentOpsObject><Url>https://currentops.com/unit/us/army/38-id/hhbn</Url><NameNode>Headquarters and Headquarters Battalion, 38th ID
                            U.S. Army</NameNode><FullName>Headquarters and Headquarters Battalion, 38th ID, U.S. Army</FullName><SplitName>Headquarters and Headquarters Battalion, 38th ID</SplitName><Service>U.S. Army</Service><LogoUrl/><Locations><LocationObject><DateRange>... - Present</DateRange><BaseName>Division Armory</BaseName><Deployment>false</Deployment><Location>Indianapolis, Indiana, United States</Location><IsCurrent>true</IsCurrent><Url>https://currentops.com/installations/us/in/division-armory</Url><Id>us/in/division-armory</Id></LocationObject></Locations><HigherHq><HigherHqObject><Url>https://currentops.com/unit/us/army/38-id</Url><Id>us/army/38-id</Id><DateRange/><IsCurrent>false</IsCurrent><HHQAcronym>38th Infantry Division</HHQAcronym><Type>Organic</Type><Name>38th Infantry Division</Name></HigherHqObject></HigherHq><Children><SubUnitObject><Url>https://currentops.com/unit/us/army/38-id/hhbn/hsc</Url><FullName>Headquarters and Support Company, Headquarters and Headquarters Battalion, 38th Infantry Division</FullName><Name>Headquarters and Support Company</Name><Id>us/army/38-id/hhbn/hsc</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/38-id/hhbn/co-a</Url><FullName>Company A, Headquarters and Headquarters Battalion, 38th Infantry Division</FullName><Name>Company A</Name><Id>us/army/38-id/hhbn/co-a</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/38-id/hhbn/co-b</Url><FullName>Company B, Headquarters and Headquarters Battalion, 38th Infantry Division</FullName><Name>Company B</Name><Id>us/army/38-id/hhbn/co-b</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/38-id/hhbn/co-c</Url><FullName>Company C, Headquarters and Headquarters Battalion, 38th Infantry Division</FullName><Name>Company C</Name><Id>us/army/38-id/hhbn/co-c</Id><IsIndirect>false</IsIndirect></SubUnitObject></Children><UnitService>Army</UnitService><UnitComponent>Volunteer</UnitComponent><UnitNGState>IN</UnitNGState></CurrentOpsObject>";
        public static string headquartersAndHqBn_1id = @"<CurrentOpsObject><Url>https://currentops.com/unit/us/army/1-id/hhbn</Url><NameNode>Headquarters and Headquarters Battalion, 1st ID
                            U.S. Army</NameNode><FullName>Headquarters and Headquarters Battalion, 1st ID, U.S. Army</FullName><SplitName>Headquarters and Headquarters Battalion, 1st ID</SplitName><Service>U.S. Army</Service><LogoUrl/><Locations><LocationObject><DateRange/><BaseName>Fort Riley</BaseName><Deployment>false</Deployment><Location>Junction City, Kansas, United States</Location><IsCurrent>false</IsCurrent><Url>https://currentops.com/installations/us/ks/fort-riley</Url><Id>us/ks/fort-riley</Id></LocationObject></Locations><HigherHq><HigherHqObject><Url>https://currentops.com/unit/us/army/1-id</Url><Id>us/army/1-id</Id><DateRange>... - Present</DateRange><IsCurrent>true</IsCurrent><HHQAcronym>1st Infantry Division</HHQAcronym><Type>Organic</Type><Name>1st Infantry Division</Name></HigherHqObject></HigherHq><Children><SubUnitObject><Url>https://currentops.com/unit/us/army/1-id/hhbn/hsc</Url><FullName>Headquarters and Support Company, Headquarters and Headquarters Battalion, 1st Infantry Division</FullName><Name>Headquarters and Support Company</Name><Id>us/army/1-id/hhbn/hsc</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/1-id/hhbn/ops-co</Url><FullName>Operations Company, Headquarters and Headquarters Battalion, 1st Infantry Division</FullName><Name>Operations Company</Name><Id>us/army/1-id/hhbn/ops-co</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/1-id/hhbn/is-co</Url><FullName>Intelligence and Sustainment Company, Headquarters and Headquarters Battalion, 1st Infantry Division</FullName><Name>Intelligence and Sustainment Company</Name><Id>us/army/1-id/hhbn/is-co</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/1-id/hhbn/sc-co</Url><FullName>Signal Company, Headquarters and Headquarters Battalion, 1st Infantry Division</FullName><Name>Signal Company</Name><Id>us/army/1-id/hhbn/sc-co</Id><IsIndirect>false</IsIndirect></SubUnitObject><SubUnitObject><Url>https://currentops.com/unit/us/army/1-id-band</Url><FullName>1st Infantry Division Band</FullName><Name>1st Infantry Division Band</Name><Id>us/army/1-id-band</Id><IsIndirect>false</IsIndirect></SubUnitObject></Children><UnitService>Army</UnitService><UnitComponent>Active</UnitComponent></CurrentOpsObject>";
    }
}
