//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        public Nullable<int> AircraftId { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public System.Guid AircraftGuid { get; set; }
        public string SeriesCode { get; set; }
        public string SeriesCodeSort { get; set; }
        public string Name { get; set; }
        public string SortName { get; set; }
        public string Mark { get; set; }
        public string Sort { get; set; }
        public string AltCode { get; set; }
        public string AltName { get; set; }
        public string AltSort { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> DoNotUse { get; set; }
    }
}
