//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltCode
    {
        public string AltCodeId { get; set; }
        public string AltCodeUse { get; set; }
        public string IndexCode10 { get; set; }
        public string IndexCode20 { get; set; }
        public string Name { get; set; }
        public string Service { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
