//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid DocumentId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Folder { get; set; }
        public string Filename { get; set; }
        public string FileType { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Reference { get; set; }
    }
}
