//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentReference
    {
        public System.Guid DocumentId { get; set; }
        public string Reference { get; set; }
        public string Source { get; set; }
        public bool CurrentRef { get; set; }
    }
}
