//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroundEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroundEquipment()
        {
            this.EquipmentOwners = new HashSet<EquipmentOwner>();
        }
    
        public Nullable<int> GroundEquipmentId { get; set; }
        public System.Guid EquipmentGuid { get; set; }
        public string Type { get; set; }
        public string Designation { get; set; }
        public string Name { get; set; }
        public string PrintName { get; set; }
        public string FamilyDesignation { get; set; }
        public string SortName { get; set; }
        public string AltCode { get; set; }
        public string AltName { get; set; }
        public string AltSort { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> DoNotUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentOwner> EquipmentOwners { get; set; }
        public virtual GroundEquipmentType GroundEquipmentType { get; set; }
    }
}
