//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int OrganisationId { get; set; }
        public string Name { get; set; }
        public bool Navy { get; set; }
        public bool Army { get; set; }
        public bool AirForce { get; set; }
        public bool Marines { get; set; }
        public bool Joint { get; set; }
        public int Rank { get; set; }
    }
}
