//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.AzureSql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.EquipmentOwners = new HashSet<EquipmentOwner>();
            this.MissionUnits = new HashSet<MissionUnit>();
            this.Relationships = new HashSet<Relationship>();
            this.Relationships1 = new HashSet<Relationship>();
            this.Ships = new HashSet<Ship>();
            this.Tennants = new HashSet<Tennant>();
            this.UnitIndexes = new HashSet<UnitIndex>();
        }
    
        public int UnitId { get; set; }
        public Nullable<int> Number { get; set; }
        public bool UseOrdinal { get; set; }
        public string Letter { get; set; }
        public string NickName { get; set; }
        public string LegacyMissionName { get; set; }
        public string MissionName { get; set; }
        public string UniqueName { get; set; }
        public string CommandName { get; set; }
        public string UnitTypeVariant { get; set; }
        public int ServiceIdx { get; set; }
        public int ServiceTypeIdx { get; set; }
        public string TerritorialDesignation { get; set; }
        public System.Guid UnitGuid { get; set; }
        public string RankSymbol { get; set; }
        public Nullable<int> AdminCorpsId { get; set; }
        public bool CanHide { get; set; }
        public Nullable<bool> Decommissioned { get; set; }
        public string Language { get; set; }
        public string Notes { get; set; }
    
        public virtual AdminCorp AdminCorp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentOwner> EquipmentOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionUnit> MissionUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationships1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship> Ships { get; set; }
        public virtual TaskForce TaskForce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tennant> Tennants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitIndex> UnitIndexes { get; set; }
    }
}
