//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminCorp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminCorp()
        {
            this.Units = new HashSet<Unit>();
        }
    
        public int AdminCorpsId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> ParentUnitId { get; set; }
        public string Lookup { get; set; }
        public Nullable<int> ParentAdminCorpsId { get; set; }
        public string SortName { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
