//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aircraft()
        {
            this.EquipmentOwners = new HashSet<EquipmentOwner>();
        }
    
        public Nullable<int> AircraftId { get; set; }
        public System.Guid AircraftGuid { get; set; }
        public string Name { get; set; }
        public string Mark { get; set; }
        public string Sort { get; set; }
        public string AltCode { get; set; }
        public string AltName { get; set; }
        public string AltSort { get; set; }
        public string SortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentOwner> EquipmentOwners { get; set; }
    }
}
