//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Base()
        {
            this.SubFacilities = new HashSet<Base>();
            this.Tennants = new HashSet<Tennant>();
        }
    
        public int BaseId { get; set; }
        public string SortName { get; set; }
        public string Prefix { get; set; }
        public string Name { get; set; }
        public string Suffix { get; set; }
        public string AltName { get; set; }
        public string IATACode { get; set; }
        public string ICAOCode { get; set; }
        public string FAACode { get; set; }
        public string AFDCode { get; set; }
        public Nullable<int> ParentBaseId { get; set; }
        public string CommissionedName { get; set; }
        public Nullable<System.Guid> ShipId { get; set; }
        public string City { get; set; }
        public string ISO3166 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base> SubFacilities { get; set; }
        public virtual Base ParentBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tennant> Tennants { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
