//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mission()
        {
            this.MissionUnits = new HashSet<MissionUnit>();
        }
    
        public int MissionId { get; set; }
        public string DisplayName { get; set; }
        public string FullName { get; set; }
        public string Notes { get; set; }
        public string AltShortForm { get; set; }
        public string Structure { get; set; }
        public string ShortForm { get; set; }
        public string MainMission { get; set; }
        public string MissionVariant { get; set; }
        public string SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionUnit> MissionUnits { get; set; }
    }
}
