//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionUnit
    {
        public int MissionId { get; set; }
        public int UnitId { get; set; }
        public string MissionVariant { get; set; }
        public string Notes { get; set; }
        public bool IsAssociate { get; set; }
    
        public virtual Mission Mission { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
