//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rank()
        {
            this.Units = new HashSet<Unit>();
        }
    
        public string Symbol { get; set; }
        public string Army { get; set; }
        public string Navy { get; set; }
        public string AirForce { get; set; }
        public string Joint { get; set; }
        public string Rank1 { get; set; }
        public Nullable<int> RankLevel { get; set; }
        public Nullable<bool> InUse { get; set; }
        public string NavyRank { get; set; }
        public string NavyRankAbbrev { get; set; }
        public string ArmyRank { get; set; }
        public string ArmyRankAbbrev { get; set; }
        public string AirForceRank { get; set; }
        public string AirForceRankAbbrev { get; set; }
        public string MarineRank { get; set; }
        public string MarineRankAbbrev { get; set; }
        public string Civil { get; set; }
        public string CivilRank { get; set; }
        public string CivilRankAbbrev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
    }
}
