//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipClassMember
    {
        public System.Guid ShipId { get; set; }
        public int ShipClassId { get; set; }
        public bool IsLeadBoat { get; set; }
    
        public virtual Ship Ship { get; set; }
        public virtual ShipClass ShipClass { get; set; }
    }
}
