//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.HasBecome = new HashSet<Ship>();
            this.ShipClassMembers = new HashSet<ShipClassMember>();
            this.Bases = new HashSet<Base>();
        }
    
        public System.Guid ShipId { get; set; }
        public int ShipPrefixId { get; set; }
        public string Name { get; set; }
        public string HCS { get; set; }
        public Nullable<int> HCSNumber { get; set; }
        public string PennantCode { get; set; }
        public Nullable<int> PennantNumber { get; set; }
        public bool IsBase { get; set; }
        public string AltName { get; set; }
        public string AltHCS { get; set; }
        public Nullable<int> AltHCSNumber { get; set; }
        public bool IsInactive { get; set; }
        public Nullable<System.Guid> NewShipId { get; set; }
        public Nullable<System.DateTime> Commissioned { get; set; }
        public Nullable<System.DateTime> Decommissioned { get; set; }
        public Nullable<int> ShipClassId { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship> HasBecome { get; set; }
        public virtual Ship WasPreviously { get; set; }
        public virtual ShipPrefix ShipPrefix { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipClassMember> ShipClassMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base> Bases { get; set; }
    }
}
