//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskForce
    {
        public int UnitId { get; set; }
        public string TaskForceName { get; set; }
        public Nullable<int> TaskForceNo { get; set; }
        public Nullable<int> TaskGroup { get; set; }
        public Nullable<int> TaskUnit { get; set; }
        public Nullable<int> TaskElement { get; set; }
        public string SortName { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
