//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tennant
    {
        public int TennancyId { get; set; }
        public int BaseId { get; set; }
        public int UnitId { get; set; }
        public bool IsHost { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Base Base { get; set; }
    }
}
