//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.RelationshipsTo = new HashSet<Relationship>();
            this.RelationshipsFrom = new HashSet<Relationship>();
            this.UnitIndexes = new HashSet<UnitIndex>();
        }
    
        public int UnitId { get; set; }
        public Nullable<int> Number { get; set; }
        public bool UseOrdinal { get; set; }
        public string MissionName { get; set; }
        public string UniqueName { get; set; }
        public int ServiceIdx { get; set; }
        public int ServiceTypeIdx { get; set; }
        public string TerritorialDesignation { get; set; }
        public System.Guid UnitGuid { get; set; }
        public string RankSymbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> RelationshipsTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> RelationshipsFrom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitIndex> UnitIndexes { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
