//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liaison.Data.Sql.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitIndex
    {
        public int UnitIndexId { get; set; }
        public string IndexCode { get; set; }
        public Nullable<System.Guid> UnitGuid { get; set; }
        public int UnitId { get; set; }
        public bool IsSortIndex { get; set; }
        public bool IsDisplayIndex { get; set; }
        public bool IsAlt { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool IsPlaceholder { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
